### ISSUE TITLE
[Question] A question about introducing black for code format

### ISSUE THREAD

**Issue by ChenZiHong-Gavin** [apache/incubator-hugegraph-ai#46]
### Problem Type (问题类型)

configs (配置项 / 文档相关)

### Before submit

- [X] I had searched in the [issues](https://github.com/apache/incubator-hugegraph-ai/issues) and found no similar issues.

### Environment (环境信息)

- Server Version: 1.x.x
- Toolchain Version: 1.x.x
- Data Size: xx vertices, xx edges >

### Your Question (问题描述)

I am thinking about introducing BLACK for code check but still confused about the process.

I also noticed that there's a **style script** already using BLACK, refer: https://github.com/apache/incubator-hugegraph-ai/blob/main/style/code_format_and_analysis.sh

This script is used in the pylint.yml workflow, but only the pylint functionality is enabled. Should I create a new workflow for using BLACK, following the structure of pylint.yml, or should I modify pylint.yml to make it capable of performing code formatting tasks as well?

**Comment by ChenZiHong-Gavin** [comment]
> @ChenZiHong-Gavin 你好! 我是Dosu，一个可以帮助你解决错误、回答问题并成为贡献者的机器人。我将在等待人类维护者的过程中协助你。
> 
> You should modify `pylint.yml` to include code formatting tasks as well. The provided script `style/code_format_and_analysis.sh` already supports running both BLACK and PYLINT together or separately based on the provided command-line arguments. This indicates that the workflow can be combined.
> 
> Here is an example of how you might modify `pylint.yml` to include BLACK:
> 
> ```yaml
> name: "Lint and Format"
> 
> on:
>   push:
>     branches:
>       - 'release-*'
>   pull_request:
> 
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     strategy:
>       matrix:
>         python-version: ["3.9", "3.10"]
>     steps:
>     - uses: actions/checkout@v4
>     - name: Set up Python ${{ matrix.python-version }}
>       uses: actions/setup-python@v3
>       with:
>         python-version: ${{ matrix.python-version }}
>     - name: Install dependencies
>       run: |
>         python -m pip install --upgrade pip
>         pip install black pylint pytest
>         pip install -r ./hugegraph-llm/requirements.txt 
>         pip install -r ./hugegraph-llm/llm_api/requirements.txt
>         pip install -r ./hugegraph-python-client/requirements.txt
>     - name: Run code format and analysis
>       run: |
>         chmod +x style/code_format_and_analysis.sh
>         ./style/code_format_and_analysis.sh -b -p
> ```
> 
> This workflow will run both BLACK and PYLINT as specified in the `style/code_format_and_analysis.sh` script [[1]](https://github.com/apache/incubator-hugegraph-ai/blob/main/style/code_format_and_analysis.sh?rgh-link-date=2024-05-29T07%3A14%3A29Z)[[2]](https://github.com/apache/incubator-hugegraph-ai/blob/main/.github/workflows/pylint.yml?rgh-link-date=2024-05-29T07%3A14%3A29Z).
> 
> #### Details
> **About Dosu** This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> _To continue the conversation, mention @dosu._

it makes sense

**Comment by ChenZiHong-Gavin** [comment]
Also, BLACK provides GitHub Actions integration(https://black.readthedocs.io/en/stable/integrations/github_actions.html), and i believe it's better because its flexibility

**Comment by imbajin** [comment]
@dosu we used the action(black CI) but it was banned by Apache's action rule, can you find examples of other Apache projects(in GitHub) using black as a code CI check or how to correctly reference black?
